name: Actions workflow
on: [push]
jobs:
  run-github-actions-repo:
    runs-on: ubuntu-latest

    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name:  List files after
        run: |
          pwd
          ls
      - name: demo action access input
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Niva
      - name: Access output
        run: echo "${{ steps.greet.outputs.time }}"
